### ISSUE TITLE
Error after surfing to the site

### ISSUE THREAD

**Issue by xigolle** [mathiassamyn/PortGame#8]
I get the following error in the logs when I go to the first page:
![image](https://user-images.githubusercontent.com/4833546/26880798-ec5dac12-4b95-11e7-85e3-d5ce0da936ef.png)

This happend after I created data in the SQL database. 
Maybe somedata is not in the correct format. Possibillity to provide test data ?

**Comment by mathiassamyn** [comment]
With the first page, you mean the login screen? The database queries should be fine, as they are the queries our current database is built on.

**Comment by mathiassamyn** [comment]
I just remembered that these are expected errors, there is nothing wrong when these appear when you go to the login page.
